### ISSUE TITLE
Feedback Datadashboard

### ISSUE THREAD

**Issue by nerdale** [Alterna87/cdmx-2018-06-bc-core-am-data-dashboard#16]
Queridas @Alterna87 y @AnndyGrs 
Estuve revisando el proyecto entregado y tengo algunos comentarios:

1. Felicitaciones por tener data dinámica, a pesar de no tener toda la información que se solicitaba, al menos lograron sacar lo básico consumiendo la información presente en el archivo Json.

2. Muy buen readme, sólo faltó indicar los pasos básicos para el uso e instalación del proyecto, recuerden que viene en la rúbrica de niveles. Si bien explican como un usuario puede hacer uso de este, el hecho de estar en una plataforma open source como github automaticamente hace el proyecto visible a muchos desarrolladores, por lo que faltan los pasos a estos usuarios en caso que se animen a probar el datadashboard o mejorarlo.

3. Muy bien por configurar linter, pero les quedaron errores/warnings que no resolvieron, lo esencial del linter es poder visibilizar y resolver esos problemas.

4. Si bien no pasan todos los test, si se nota que en un momento existió orientación a test pero que a medida que el proyecto creció esto se dejó de lado. Algo totalmente mejorable, deben trabajarlo desde ahora ya. :rocket:

5. Ojo con la indentación, es un factor que si bien no se evalua, es muy importante al momento de recibir codereview o feedback de otro desarrollador, el archivo **index.html** es el que tiene más problemas.

6. Esta vez pasé por alto el tema de la tipografía, pero a futuro no puede pasar que trabajen para un cliente que ya tiene un manual de marca definido, y no utilicen la tipografía que ellos indican, en este caso solo utilizaron los colores de Laboratoria, así que más cuidado con eso para la próxima.

7. No es responsive :cry: 

8. Si bien usa nombres descriptivos en la mayoría de su proyecto, hay ciertas variables que no se logran comprender a primera vista por su nombre como **j** o **i** (data.js, l{inea 27 y 28) por ejemplo, entiendo que son contadores pero su nombre no dice mucho.

9. En el css hay algunos elementos que tienen las mismas propiedades, las podrían haber agrupados, pero van por buen camino.

Vamos con todo el power para el siguiente proyecto! ustedes pueden :rocket:

**Comment by anndygrs** [comment]
Gracias por tu feedback, Ale!

Había una versión menos completa que sí es responsive y tiene la tipografía de Laboratoria, tuvimos un problema a último minuto con el Git y subimos esta última versión, yo ya estoy trabajando en esos aspectos, y también checo la identación del HTML y las clases del CSS.

:kissing_heart:

**Comment by nerdale** [comment]
Vamos con toooodooo las extraño :cry:
