### ISSUE TITLE
Sprint 1 - Falta generaciòn 

### ISSUE THREAD

**Issue by anndygrs** [Alterna87/cdmx-2018-06-bc-core-am-data-dashboard#2]
Falta la visualizaciòn de las generaciones en cada sede :)

**Comment by francisvelueta** [comment]
Sprnt 1 Incompleto - 

- [x] Falta mostrar generaciones

- [x] Poner más maquetado

**Comment by Alterna87** [comment]
listo esta parte 👍

**Comment by francisvelueta** [comment]
listo esta parte 👍
