### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [Alterna87/cdmx-2018-06-bc-core-am-data-dashboard#8]
Hola @Alterna87 y @AnndyGrs 

He estado revisando el proyecto y les recomiendo ya comenzar a plasmar tanto lo visual como lo funcional, ya saben entrar a la data y sacar la información que necesitan, deben comenzar a darle forma al proyecto en honor al tiempo.

Les recomiendo eso si, tener mucho cuidado con la indentación para mantener el orden del código tanto para ustedes mismas como para quien les de feedback/codereview :smile: 

Buen trabajo colaborativo en github.

--
Alexandra N.-

**Comment by anndygrs** [comment]
Gracias Alexandra :)

**Comment by nerdale** [comment]
Daré por cerrado el issue :smile: 
:rocket:
